/* eslint-disable */
/**
 * Generated API types — stub until `npx convex dev` generates real types.
 */
import type { ApiFromModules } from "convex/server";
import type { AnyDataModel } from "convex/server";

// Placeholder — real types generated by `npx convex dev`
export type API = Record<string, Record<string, unknown>>;
export default API;
