import type { Metadata } from "next";
import { headers } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { ConvexClientProvider } from "@/components/convex-provider";
import { ServiceWorkerRegister } from "@/components/service-worker-register";
import { OfflineBanner } from "@/components/offline-banner";
import { ErrorBoundary } from "@/components/error-boundary";
import { ConvexErrorBoundary } from "@/components/convex-error-boundary";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WOWWAI",
  description: "Ways of Working With AI — Project management + workflow control centre",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // US-058: Nonce-based CSP implemented
  // The nonce is generated in middleware.ts and set in the CSP header.
  // Next.js automatically extracts the nonce from the CSP header and applies it to:
  //   - Framework scripts (React, Next.js runtime)
  //   - Page-specific JavaScript bundles
  //   - Inline styles and scripts generated by Next.js
  //
  // The nonce is available via headers() if needed for custom Script components:
  // const headersList = await headers();
  // const nonce = headersList.get("x-nonce") || undefined;

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#09090b" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Root error boundary — catches catastrophic errors before anything renders */}
        <ErrorBoundary>
          <ConvexClientProvider>
            {/* Convex-aware boundary — detects backend connection failures */}
            <ConvexErrorBoundary>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <OfflineBanner />
                {children}
                <ServiceWorkerRegister />
                {/* Toast notifications for mutation feedback */}
                <Toaster richColors position="bottom-right" />
              </ThemeProvider>
            </ConvexErrorBoundary>
          </ConvexClientProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
